import { Plus, Trash2, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import api from '../lib/api.js'
import { localDateInput } from '../lib/date.js'
const rupiah=(v)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(v||0)
const initial={kategori:'Operasional',keterangan:'',nominal:'',tanggal_pengeluaran:localDateInput(),rutin:'0',catatan:''}
export default function Expenses(){const[items,setItems]=useState([]);const[modal,setModal]=useState(false);const[form,setForm]=useState(initial);const[error,setError]=useState('');const[notice,setNotice]=useState('');function load(){api.get('/pengeluaran?per_page=100').then(({data})=>setItems(data.data)).catch(()=>setError('Data pengeluaran gagal dimuat.'))}useEffect(()=>{load()},[])
async function submit(e){e.preventDefault();try{await api.post('/pengeluaran',{...form,nominal:Number(form.nominal),rutin:form.rutin==='1'});setModal(false);setForm(initial);setNotice('Pengeluaran berhasil dicatat.');load()}catch(err){setError(Object.values(err.response?.data?.errors||{}).flat()[0]||'Pengeluaran gagal disimpan.')}}async function remove(id){if(!confirm('Hapus data pengeluaran ini?'))return;await api.delete(`/pengeluaran/${id}`);load()}
return <div className="page-stack"><section className="page-heading"><div><span className="eyebrow">TRANSAKSI KELUAR</span><h2>Pengeluaran RT</h2><p>Catat biaya rutin dan kebutuhan lingkungan lainnya.</p></div><button className="button primary" onClick={()=>setModal(true)}><Plus size={18}/>Tambah Pengeluaran</button></section>{notice&&<div className="alert success">{notice}</div>}{error&&<div className="alert error">{error}</div>}<section className="panel"><div className="table-wrap"><table><thead><tr><th>Tanggal</th><th>Kategori</th><th>Keterangan</th><th>Sifat</th><th>Nominal</th><th></th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td>{new Date(i.tanggal_pengeluaran+'T00:00:00').toLocaleDateString('id-ID')}</td><td>{i.kategori}</td><td><strong>{i.keterangan}</strong></td><td><span className={`badge ${i.rutin?'tetap':'neutral'}`}>{i.rutin?'Rutin':'Tidak rutin'}</span></td><td><strong>{rupiah(i.nominal)}</strong></td><td><button className="danger-icon" onClick={()=>remove(i.id)}><Trash2 size={16}/></button></td></tr>)}{!items.length&&<tr><td colSpan="6" className="empty">Belum ada pengeluaran.</td></tr>}</tbody></table></div></section>{modal&&<div className="modal-layer"><div className="modal"><div className="modal-head"><div><span className="eyebrow">DATA BARU</span><h3>Tambah Pengeluaran</h3></div><button onClick={()=>setModal(false)}><X/></button></div><form className="form-grid" onSubmit={submit}><label>Kategori<input value={form.kategori} onChange={e=>setForm({...form,kategori:e.target.value})} required/></label><label>Tanggal<input type="date" value={form.tanggal_pengeluaran} onChange={e=>setForm({...form,tanggal_pengeluaran:e.target.value})} required/></label><label className="full">Keterangan<input value={form.keterangan} onChange={e=>setForm({...form,keterangan:e.target.value})} required/></label><label>Nominal<input type="number" min="1" value={form.nominal} onChange={e=>setForm({...form,nominal:e.target.value})} required/></label><label>Sifat pengeluaran<select value={form.rutin} onChange={e=>setForm({...form,rutin:e.target.value})}><option value="0">Tidak rutin</option><option value="1">Rutin bulanan</option></select></label><label className="full">Catatan<textarea value={form.catatan} onChange={e=>setForm({...form,catatan:e.target.value})}/></label><div className="modal-actions full"><button type="button" className="button secondary" onClick={()=>setModal(false)}>Batal</button><button className="button primary">Simpan Pengeluaran</button></div></form></div></div>}</div>}
